title: A Photo a Day
description: <a href="www.google.com">TEST</a> Aging-process prediction with learning tools. Created by [Jacob Sela](mailto:jacob.sela123@gmail.com) and [Shavit Borisov](mailto:shavitborisov@gmail.com). Supervised by [Elad Richardson](mailto:elad.richardson@gmail.com).
theme: jekyll-theme-slate
markdown: kramdown
